# Generated by Django 4.2.6 on 2023-10-31 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225, unique=True)),
                ('email', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('image', models.ImageField(default='/images/default_chef.png', upload_to='images/')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=-1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('claps', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='/images/default_rec.png', upload_to='images/')),
                ('total_price', models.DecimalField(decimal_places=2, default=-1, max_digits=6)),
                ('chef', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chef.chef')),
                ('ingredients', models.ManyToManyField(to='chef.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('vacancies', models.IntegerField()),
                ('filled_seats', models.IntegerField()),
                ('additional_info', models.TextField()),
                ('chef', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chef.chef')),
            ],
        ),
    ]
